name: rl-assign
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
    - pip:
    - torch
    - gym
    - numpy
    - pandas
    - matplotlib
    - tensorboard
    - gym-anytrading
    - ipykernel
