name: rl-assign
channels:
  - anaconda
dependencies:
  - python=3.8
  - pip
    - pip:
      - torch
      - gym
      - numpy
      - pandas
      - matplotlib
      - tensorboard
      - requests
      - ipykernel
